# Site settings
title: Behind The Keyboard
email: xavier.decoret@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes about computers and my time as a programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xadeck.github.io" # the base hostname & protocol for your site
github_username:  Xadeck

# Build settings
markdown: kramdown

exclude: [Gemfile, Gemfile.lock, Rakefile]

# Enabled plugins
gems: 
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-terminal